# Stubs for _csv (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Undefined

QUOTE_ALL = Undefined(int)
QUOTE_MINIMAL = Undefined(int)
QUOTE_NONE = Undefined(int)
QUOTE_NONNUMERIC = Undefined(int)
_dialects = Undefined(Any)

def field_size_limit(new_limit=Undefined): pass
def get_dialect(name): pass
def list_dialects(): pass
def reader(csvfile, dialect=Undefined, **fmtparams=Undefined): pass
def register_dialect(name, dialect=Undefined, **fmtparams=Undefined): pass
def unregister_dialect(name): pass
def writer(csvfile, dialect=Undefined, **fmtparams=Undefined): pass

class Dialect:
    delimiter = Undefined(Any)
    doublequote = Undefined(Any)
    escapechar = Undefined(Any)
    lineterminator = Undefined(Any)
    quotechar = Undefined(Any)
    quoting = Undefined(Any)
    skipinitialspace = Undefined(Any)
    strict = Undefined(Any)
    def __init__(self, *args, **kwargs): pass

class Error(Exception): pass
