# Stubs for _elementtree (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Undefined

def SubElement(parent, tag, attrib=Undefined, **extra): pass

class Element:
    def __init__(self, tag, attrib=Undefined, **extra): pass
    def append(self, *args, **kwargs): pass
    def clear(self, *args, **kwargs): pass
    def extend(self, *args, **kwargs): pass
    def find(self, *args, **kwargs): pass
    def findall(self, *args, **kwargs): pass
    def findtext(self, match, default=Undefined, namespaces=Undefined): pass
    def get(self, *args, **kwargs): pass
    def getchildren(self): pass
    def getiterator(self, tag=Undefined): pass
    def insert(self, *args, **kwargs): pass
    def items(self, *args, **kwargs): pass
    def iter(self, *args, **kwargs): pass
    def iterfind(self, match, namespaces=Undefined): pass
    def itertext(self): pass
    def keys(self): pass
    def makeelement(self, tag, attrib): pass
    def remove(self, *args, **kwargs): pass
    def set(self, *args, **kwargs): pass
    def __copy__(self): pass
    def __deepcopy__(self): pass
    def __delattr__(self, name): pass
    def __delitem__(self, name): pass
    def __getitem__(self, name): pass
    def __getstate__(self): pass
    def __len__(self): pass
    def __setattr__(self, name, value): pass
    def __setitem__(self, index, object): pass
    def __setstate__(self, state): pass
    def __sizeof__(self): pass

class ParseError(SyntaxError): pass

class TreeBuilder:
    def __init__(self, element_factory=Undefined): pass
    def close(self, *args, **kwargs): pass
    def data(self, data): pass
    def end(self, tag): pass
    def start(self, *args, **kwargs): pass

class XMLParser:
    target = Undefined(Any)
    entity = Undefined(Any)
    version = Undefined(Any)
    def __init__(self, html=Undefined, target=Undefined, encoding=Undefined): pass
    def _parse_whole(self, *args, **kwargs): pass
    def _setevents(self, *args, **kwargs): pass
    def close(self, *args, **kwargs): pass
    def doctype(self, name, pubid, system): pass
    def feed(self, data): pass
