# Stubs for _locale (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Iterable

ABDAY_1 = Undefined(int)
ABDAY_2 = Undefined(int)
ABDAY_3 = Undefined(int)
ABDAY_4 = Undefined(int)
ABDAY_5 = Undefined(int)
ABDAY_6 = Undefined(int)
ABDAY_7 = Undefined(int)
ABMON_1 = Undefined(int)
ABMON_10 = Undefined(int)
ABMON_11 = Undefined(int)
ABMON_12 = Undefined(int)
ABMON_2 = Undefined(int)
ABMON_3 = Undefined(int)
ABMON_4 = Undefined(int)
ABMON_5 = Undefined(int)
ABMON_6 = Undefined(int)
ABMON_7 = Undefined(int)
ABMON_8 = Undefined(int)
ABMON_9 = Undefined(int)
ALT_DIGITS = Undefined(int)
AM_STR = Undefined(int)
CHAR_MAX = Undefined(int)
CODESET = Undefined(int)
CRNCYSTR = Undefined(int)
DAY_1 = Undefined(int)
DAY_2 = Undefined(int)
DAY_3 = Undefined(int)
DAY_4 = Undefined(int)
DAY_5 = Undefined(int)
DAY_6 = Undefined(int)
DAY_7 = Undefined(int)
D_FMT = Undefined(int)
D_T_FMT = Undefined(int)
ERA = Undefined(int)
ERA_D_FMT = Undefined(int)
ERA_D_T_FMT = Undefined(int)
ERA_T_FMT = Undefined(int)
LC_ALL = Undefined(int)
LC_COLLATE = Undefined(int)
LC_CTYPE = Undefined(int)
LC_MESSAGES = Undefined(int)
LC_MONETARY = Undefined(int)
LC_NUMERIC = Undefined(int)
LC_TIME = Undefined(int)
MON_1 = Undefined(int)
MON_10 = Undefined(int)
MON_11 = Undefined(int)
MON_12 = Undefined(int)
MON_2 = Undefined(int)
MON_3 = Undefined(int)
MON_4 = Undefined(int)
MON_5 = Undefined(int)
MON_6 = Undefined(int)
MON_7 = Undefined(int)
MON_8 = Undefined(int)
MON_9 = Undefined(int)
NOEXPR = Undefined(int)
PM_STR = Undefined(int)
RADIXCHAR = Undefined(int)
THOUSEP = Undefined(int)
T_FMT = Undefined(int)
T_FMT_AMPM = Undefined(int)
YESEXPR = Undefined(int)
_DATE_FMT = Undefined(int)

def bind_textdomain_codeset(domain, codeset): pass
def bindtextdomain(domain, dir): pass
def dcgettext(domain, msg, category): pass
def dgettext(domain, msg): pass
def gettext(msg): pass
def localeconv(): pass
def nl_langinfo(key): pass
def setlocale(category: int, locale: Iterable[str] = None) -> str: pass
def strcoll(string1, string2) -> int: pass
def strxfrm(string): pass
def textdomain(domain): pass

class Error(Exception): pass
