# Stubs for _ssl (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Undefined

ALERT_DESCRIPTION_ACCESS_DENIED = Undefined(int)
ALERT_DESCRIPTION_BAD_CERTIFICATE = Undefined(int)
ALERT_DESCRIPTION_BAD_CERTIFICATE_HASH_VALUE = Undefined(int)
ALERT_DESCRIPTION_BAD_CERTIFICATE_STATUS_RESPONSE = Undefined(int)
ALERT_DESCRIPTION_BAD_RECORD_MAC = Undefined(int)
ALERT_DESCRIPTION_CERTIFICATE_EXPIRED = Undefined(int)
ALERT_DESCRIPTION_CERTIFICATE_REVOKED = Undefined(int)
ALERT_DESCRIPTION_CERTIFICATE_UNKNOWN = Undefined(int)
ALERT_DESCRIPTION_CERTIFICATE_UNOBTAINABLE = Undefined(int)
ALERT_DESCRIPTION_CLOSE_NOTIFY = Undefined(int)
ALERT_DESCRIPTION_DECODE_ERROR = Undefined(int)
ALERT_DESCRIPTION_DECOMPRESSION_FAILURE = Undefined(int)
ALERT_DESCRIPTION_DECRYPT_ERROR = Undefined(int)
ALERT_DESCRIPTION_HANDSHAKE_FAILURE = Undefined(int)
ALERT_DESCRIPTION_ILLEGAL_PARAMETER = Undefined(int)
ALERT_DESCRIPTION_INSUFFICIENT_SECURITY = Undefined(int)
ALERT_DESCRIPTION_INTERNAL_ERROR = Undefined(int)
ALERT_DESCRIPTION_NO_RENEGOTIATION = Undefined(int)
ALERT_DESCRIPTION_PROTOCOL_VERSION = Undefined(int)
ALERT_DESCRIPTION_RECORD_OVERFLOW = Undefined(int)
ALERT_DESCRIPTION_UNEXPECTED_MESSAGE = Undefined(int)
ALERT_DESCRIPTION_UNKNOWN_CA = Undefined(int)
ALERT_DESCRIPTION_UNKNOWN_PSK_IDENTITY = Undefined(int)
ALERT_DESCRIPTION_UNRECOGNIZED_NAME = Undefined(int)
ALERT_DESCRIPTION_UNSUPPORTED_CERTIFICATE = Undefined(int)
ALERT_DESCRIPTION_UNSUPPORTED_EXTENSION = Undefined(int)
ALERT_DESCRIPTION_USER_CANCELLED = Undefined(int)
CERT_NONE = Undefined(int)
CERT_OPTIONAL = Undefined(int)
CERT_REQUIRED = Undefined(int)
HAS_ECDH = Undefined(bool)
HAS_NPN = Undefined(bool)
HAS_SNI = Undefined(bool)
HAS_TLS_UNIQUE = Undefined(bool)
OPENSSL_VERSION = Undefined(str)
OPENSSL_VERSION_INFO = Undefined(Any)
OPENSSL_VERSION_NUMBER = Undefined(int)
OP_ALL = Undefined(int)
OP_CIPHER_SERVER_PREFERENCE = Undefined(int)
OP_NO_COMPRESSION = Undefined(int)
OP_NO_SSLv2 = Undefined(int)
OP_NO_SSLv3 = Undefined(int)
OP_NO_TLSv1 = Undefined(int)
OP_NO_TLSv1_1 = Undefined(int)
OP_NO_TLSv1_2 = Undefined(int)
OP_SINGLE_DH_USE = Undefined(int)
OP_SINGLE_ECDH_USE = Undefined(int)
PROTOCOL_SSLv23 = Undefined(int)
PROTOCOL_SSLv3 = Undefined(int)
PROTOCOL_TLSv1 = Undefined(int)
PROTOCOL_TLSv1_1 = Undefined(int)
PROTOCOL_TLSv1_2 = Undefined(int)
SSL_ERROR_EOF = Undefined(int)
SSL_ERROR_INVALID_ERROR_CODE = Undefined(int)
SSL_ERROR_SSL = Undefined(int)
SSL_ERROR_SYSCALL = Undefined(int)
SSL_ERROR_WANT_CONNECT = Undefined(int)
SSL_ERROR_WANT_READ = Undefined(int)
SSL_ERROR_WANT_WRITE = Undefined(int)
SSL_ERROR_WANT_X509_LOOKUP = Undefined(int)
SSL_ERROR_ZERO_RETURN = Undefined(int)
VERIFY_CRL_CHECK_CHAIN = Undefined(int)
VERIFY_CRL_CHECK_LEAF = Undefined(int)
VERIFY_DEFAULT = Undefined(int)
VERIFY_X509_STRICT = Undefined(int)
_OPENSSL_API_VERSION = Undefined(Any)
err_codes_to_names = Undefined(Any)
err_names_to_codes = Undefined(Any)
lib_codes_to_names = Undefined(Any)

def RAND_add(string, entropy): pass
def RAND_bytes(n): pass
def RAND_egd(path): pass
def RAND_pseudo_bytes(n): pass
def RAND_status(): pass
def _test_decode_cert(*args, **kwargs): pass
def get_default_verify_paths(): pass
def nid2obj(nid): pass
def txt2obj(txt, name=False): pass

class SSLEOFError(SSLError): pass

class SSLError(OSError): pass

class SSLSyscallError(SSLError): pass

class SSLWantReadError(SSLError): pass

class SSLWantWriteError(SSLError): pass

class SSLZeroReturnError(SSLError): pass

class _SSLContext:
    check_hostname = Undefined(Any)
    options = Undefined(Any)
    verify_flags = Undefined(Any)
    verify_mode = Undefined(Any)
    def __init__(self, *args, **kwargs): pass
    def _set_npn_protocols(self, *args, **kwargs): pass
    def _wrap_socket(self, *args, **kwargs): pass
    def cert_store_stats(self): pass
    def get_ca_certs(self, binary_form=False): pass
    def load_cert_chain(self, *args, **kwargs): pass
    def load_dh_params(self, *args, **kwargs): pass
    def load_verify_locations(self, *args, **kwargs): pass
    def session_stats(self, *args, **kwargs): pass
    def set_ciphers(self, *args, **kwargs): pass
    def set_default_verify_paths(self, *args, **kwargs): pass
    def set_ecdh_curve(self, *args, **kwargs): pass
    def set_servername_callback(self, method): pass

class _SSLSocket:
    context = Undefined(Any)
    def cipher(self, *args, **kwargs): pass
    def compression(self, *args, **kwargs): pass
    def do_handshake(self, *args, **kwargs): pass
    def peer_certificate(self, *args, **kwargs): pass
    def pending(self): pass
    def read(self, *args, **kwargs): pass
    def selected_npn_protocol(self, *args, **kwargs): pass
    def shutdown(self, s): pass
    def tls_unique_cb(self): pass
    def write(self, s): pass
