# Stubs for csv (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

QUOTE_ALL = ...  # type: int
QUOTE_MINIMAL = ...  # type: int
QUOTE_NONE = ...  # type: int
QUOTE_NONNUMERIC = ...  # type: int

class Error(Exception): pass

def writer(csvfile, dialect=..., **fmtparams): pass
def reader(csvfile, dialect=..., **fmtparams): pass
def register_dialect(name, dialect=..., **fmtparams): pass
def unregister_dialect(name): pass
def get_dialect(name): pass
def list_dialects(): pass
def field_size_limit(new_limit=...): pass

class Dialect:
    delimiter = ...  # type: Any
    quotechar = ...  # type: Any
    escapechar = ...  # type: Any
    doublequote = ...  # type: Any
    skipinitialspace = ...  # type: Any
    lineterminator = ...  # type: Any
    quoting = ...  # type: Any
    def __init__(self): pass

class excel(Dialect):
    delimiter = ...  # type: Any
    quotechar = ...  # type: Any
    doublequote = ...  # type: Any
    skipinitialspace = ...  # type: Any
    lineterminator = ...  # type: Any
    quoting = ...  # type: Any

class excel_tab(excel):
    delimiter = ...  # type: Any

class unix_dialect(Dialect):
    delimiter = ...  # type: Any
    quotechar = ...  # type: Any
    doublequote = ...  # type: Any
    skipinitialspace = ...  # type: Any
    lineterminator = ...  # type: Any
    quoting = ...  # type: Any

class DictReader:
    restkey = ...  # type: Any
    restval = ...  # type: Any
    reader = ...  # type: Any
    dialect = ...  # type: Any
    line_num = ...  # type: Any
    fieldnames = ...  # type: Any # Actually a property
    def __init__(self, f, fieldnames=None, restkey=None, restval=None, dialect='',
                 *args, **kwds): pass
    def __iter__(self): pass
    def __next__(self): pass

class DictWriter:
    fieldnames = ...  # type: Any
    restval = ...  # type: Any
    extrasaction = ...  # type: Any
    writer = ...  # type: Any
    def __init__(self, f, fieldnames, restval='', extrasaction='', dialect='', *args, **kwds): pass
    def writeheader(self): pass
    def writerow(self, rowdict): pass
    def writerows(self, rowdicts): pass

class Sniffer:
    preferred = ...  # type: Any
    def __init__(self): pass
    def sniff(self, sample, delimiters=None): pass
    def has_header(self, sample): pass
