# Stubs for math
# Ron Murawski <ron@horizonchess.com>

# based on: http://docs.python.org/3.2/library/math.html

from typing import overload, Tuple, Iterable

# ----- variables and constants -----
e = 0.0
pi = 0.0

# ----- functions -----
def ceil(x: float) -> int: ...
def copysign(x: float, y: float) -> float: ...
def fabs(x: float) -> float: ...
def factorial(x: int) -> int: ...
def floor(x: float) -> int: ...
def fmod(x: float, y: float) -> float: ...
def frexp(x: float) -> Tuple[float, int]: ...
def fsum(iterable: Iterable) -> float: ...
def isfinite(x: float) -> bool: ...
def isinf(x: float) -> bool: ...
def isnan(x: float) -> bool: ...
def ldexp(x: float, i: int) -> float: ...
def modf(x: float) -> Tuple[float, float]: ...
def trunc(x: float) -> float: ...
def exp(x: float) -> float: ...
def expm1(x: float) -> float: ...
def log(x: float, base: float = e) -> float: ...
def log1p(x: float) -> float: ...
def log10(x: float) -> float: ...
def pow(x: float, y: float) -> float: ...
def sqrt(x: float) -> float: ...
def acos(x: float) -> float: ...
def asin(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...
def cos(x: float) -> float: ...
def hypot(x: float, y: float) -> float: ...
def sin(x: float) -> float: ...
def tan(x: float) -> float: ...
def degrees(x: float) -> float: ...
def radians(x: float) -> float: ...
def acosh(x: float) -> float: ...
def asinh(x: float) -> float: ...
def atanh(x: float) -> float: ...
def cosh(x: float) -> float: ...
def sinh(x: float) -> float: ...
def tanh(x: float) -> float: ...
def erf(x: object) -> float: ...
def erfc(x: object) -> float: ...
def gamma(x: object) -> float: ...
def lgamma(x: object) -> float: ...
