# Stubs for smtplib (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SMTPException(OSError): pass
class SMTPServerDisconnected(SMTPException): pass

class SMTPResponseException(SMTPException):
    smtp_code = ... # type: Any
    smtp_error = ... # type: Any
    args = ... # type: Any
    def __init__(self, code, msg): pass

class SMTPSenderRefused(SMTPResponseException):
    smtp_code = ... # type: Any
    smtp_error = ... # type: Any
    sender = ... # type: Any
    args = ... # type: Any
    def __init__(self, code, msg, sender): pass

class SMTPRecipientsRefused(SMTPException):
    recipients = ... # type: Any
    args = ... # type: Any
    def __init__(self, recipients): pass

class SMTPDataError(SMTPResponseException): pass
class SMTPConnectError(SMTPResponseException): pass
class SMTPHeloError(SMTPResponseException): pass
class SMTPAuthenticationError(SMTPResponseException): pass

def quoteaddr(addrstring): pass
def quotedata(data): pass

class SMTP:
    debuglevel = ... # type: Any
    file = ... # type: Any
    helo_resp = ... # type: Any
    ehlo_msg = ... # type: Any
    ehlo_resp = ... # type: Any
    does_esmtp = ... # type: Any
    default_port = ... # type: Any
    timeout = ... # type: Any
    esmtp_features = ... # type: Any
    source_address = ... # type: Any
    local_hostname = ... # type: Any
    def __init__(self, host='', port=0, local_hostname=None, timeout=...,
                 source_address=None): pass
    def __enter__(self): pass
    def __exit__(self, *args): pass
    def set_debuglevel(self, debuglevel): pass
    sock = ... # type: Any
    def connect(self, host='', port=0, source_address=None): pass
    def send(self, s): pass
    def putcmd(self, cmd, args=''): pass
    def getreply(self): pass
    def docmd(self, cmd, args=''): pass
    def helo(self, name=''): pass
    def ehlo(self, name=''): pass
    def has_extn(self, opt): pass
    def help(self, args=''): pass
    def rset(self): pass
    def noop(self): pass
    def mail(self, sender, options=...): pass
    def rcpt(self, recip, options=...): pass
    def data(self, msg): pass
    def verify(self, address): pass
    vrfy = ... # type: Any
    def expn(self, address): pass
    def ehlo_or_helo_if_needed(self): pass
    def login(self, user, password): pass
    def starttls(self, keyfile=None, certfile=None, context=None): pass
    def sendmail(self, from_addr, to_addrs, msg, mail_options=...,
                 rcpt_options=...): pass
    def send_message(self, msg, from_addr=None, to_addrs=None, mail_options=...,
                     rcpt_options=...): pass
    def close(self): pass
    def quit(self): pass

class SMTP_SSL(SMTP):
    default_port = ... # type: Any
    keyfile = ... # type: Any
    certfile = ... # type: Any
    context = ... # type: Any
    def __init__(self, host='', port=0, local_hostname=None, keyfile=None, certfile=None,
                 timeout=..., source_address=None, context=None): pass

class LMTP(SMTP):
    ehlo_msg = ... # type: Any
    def __init__(self, host='', port=..., local_hostname=None, source_address=None): pass
    sock = ... # type: Any
    file = ... # type: Any
    def connect(self, host='', port=0, source_address=None): pass
