# Stubs for unicodedata (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

ucd_3_2_0 = ... # type: Any
ucnhash_CAPI = ... # type: Any
unidata_version = ... # type: str

def bidirectional(unichr): pass
def category(unichr): pass
def combining(unichr): pass
def decimal(chr, default=...): pass
def decomposition(unichr): pass
def digit(chr, default=...): pass
def east_asian_width(unichr): pass
def lookup(name): pass
def mirrored(unichr): pass
def name(chr, default=...): pass
def normalize(form, unistr): pass
def numeric(chr, default=...): pass

class UCD:
    unidata_version = ... # type: Any
    def bidirectional(self, unichr): pass
    def category(self, unichr): pass
    def combining(self, unichr): pass
    def decimal(self, chr, default=...): pass
    def decomposition(self, unichr): pass
    def digit(self, chr, default=...): pass
    def east_asian_width(self, unichr): pass
    def lookup(self, name): pass
    def mirrored(self, unichr): pass
    def name(self, chr, default=...): pass
    def normalize(self, form, unistr): pass
    def numeric(self, chr, default=...): pass
