# Stubs for webbrowser (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Error(Exception): pass

def register(name, klass, instance=None, update_tryorder=1): pass
def get(using=None): pass
def open(url, new=0, autoraise=True): pass
def open_new(url): pass
def open_new_tab(url): pass

class BaseBrowser:
    args = ... # type: Any
    name = ... # type: Any
    basename = ... # type: Any
    def __init__(self, name=''): pass
    def open(self, url, new=0, autoraise=True): pass
    def open_new(self, url): pass
    def open_new_tab(self, url): pass

class GenericBrowser(BaseBrowser):
    name = ... # type: Any
    args = ... # type: Any
    basename = ... # type: Any
    def __init__(self, name): pass
    def open(self, url, new=0, autoraise=True): pass

class BackgroundBrowser(GenericBrowser):
    def open(self, url, new=0, autoraise=True): pass

class UnixBrowser(BaseBrowser):
    raise_opts = ... # type: Any
    background = ... # type: Any
    redirect_stdout = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    def open(self, url, new=0, autoraise=True): pass

class Mozilla(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Galeon(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    background = ... # type: Any

class Chrome(UnixBrowser):
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Opera(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Elinks(UnixBrowser):
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any
    redirect_stdout = ... # type: Any

class Konqueror(BaseBrowser):
    def open(self, url, new=0, autoraise=True): pass

class Grail(BaseBrowser):
    def open(self, url, new=0, autoraise=True): pass

class WindowsDefault(BaseBrowser):
    def open(self, url, new=0, autoraise=True): pass

class MacOSX(BaseBrowser):
    name = ... # type: Any
    def __init__(self, name): pass
    def open(self, url, new=0, autoraise=True): pass

class MacOSXOSAScript(BaseBrowser):
    def __init__(self, name): pass
    def open(self, url, new=0, autoraise=True): pass
