# Stubs for zlib (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined

DEFLATED = Undefined(int)
DEF_BUF_SIZE = Undefined(int)
DEF_MEM_LEVEL = Undefined(int)
MAX_WBITS = Undefined(int)
ZLIB_RUNTIME_VERSION = Undefined(str)
ZLIB_VERSION = Undefined(str)
Z_BEST_COMPRESSION = Undefined(int)
Z_BEST_SPEED = Undefined(int)
Z_DEFAULT_COMPRESSION = Undefined(int)
Z_DEFAULT_STRATEGY = Undefined(int)
Z_FILTERED = Undefined(int)
Z_FINISH = Undefined(int)
Z_FULL_FLUSH = Undefined(int)
Z_HUFFMAN_ONLY = Undefined(int)
Z_NO_FLUSH = Undefined(int)
Z_SYNC_FLUSH = Undefined(int)

def adler32(data, value=Undefined): pass
def compress(*args, **kwargs): pass
def compressobj(level=Undefined, method=Undefined, wbits=Undefined, memlevel=Undefined, strategy=Undefined, zdict=Undefined): pass
def crc32(*args, **kwargs): pass
def decompress(*args, **kwargs): pass
def decompressobj(wbits=Undefined, zdict=Undefined): pass

class error(Exception): pass
