# Stubs for requests.packages (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class VendorAlias:
    def __init__(self, package_names): pass
    def find_module(self, fullname, path=None): pass
    def load_module(self, name): pass
