# Stubs for textwrap (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class _unicode: ...

class TextWrapper:
    whitespace_trans = ... # type: Any
    unicode_whitespace_trans = ... # type: Any
    uspace = ... # type: Any
    wordsep_re = ... # type: Any
    wordsep_simple_re = ... # type: Any
    sentence_end_re = ... # type: Any
    width = ... # type: Any
    initial_indent = ... # type: Any
    subsequent_indent = ... # type: Any
    expand_tabs = ... # type: Any
    replace_whitespace = ... # type: Any
    fix_sentence_endings = ... # type: Any
    break_long_words = ... # type: Any
    drop_whitespace = ... # type: Any
    break_on_hyphens = ... # type: Any
    wordsep_re_uni = ... # type: Any
    wordsep_simple_re_uni = ... # type: Any
    def __init__(self, width=70, initial_indent='', subsequent_indent='', expand_tabs=True, replace_whitespace=True, fix_sentence_endings=False, break_long_words=True, drop_whitespace=True, break_on_hyphens=True): ...
    def wrap(self, text): ...
    def fill(self, text): ...

def wrap(text, width=70, **kwargs): ...
def fill(text, width=70, **kwargs): ...
def dedent(text): ...
