exclude: '^(mypyc/external/)|(mypy/typeshed/)|misc/typeshed_patches'  # Exclude all vendored code from lints
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 96ae3e5802f3fe2d551e703e18f0a367d1a81ac2  # frozen: 26.10.0
    hooks:
      - id: black
        exclude: '^(test-data/)'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f12be1ebaa5351c1fc76472de98db2c3446c8253  # frozen: v0.16.10
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 4f85d46a92dc17713078e5de73f8a13190edf6fc  # frozen: 0.38.2
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-readthedocs
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=HAX,Nam,ccompiler,keep-alives,ot,statics,whet,zar
        exclude: ^(mypy/test/|mypy/typeshed/|mypyc/test-data/|test-data/).+$
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint
        args: [
          -ignore=property "debug_build" is not defined,
          -ignore=property "allow_failure" is not defined,
          -ignore=SC2(046|086),
        ]
        additional_dependencies:
          # actionlint has a shellcheck integration which extracts shell scripts in `run:` steps from GitHub Actions
          # and checks these with shellcheck. This is arguably its most useful feature,
          # but the integration only works if shellcheck is installed
          - "github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1"
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: fa412071e4f5d44d44f9e365f4676f9df92456a2  # frozen: v1.30.1
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: bad-pr-link
        name: Bad PR link
        description: Detect PR links text that don't match their URL
        language: pygrep
        entry: '\[(\d+)\]\(https://github.com/python/mypy/pull/(?!\1/?\))\d+/?\)'
        files: CHANGELOG.md
  # Should be the last one:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

ci:
  autoupdate_schedule: quarterly
