# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
   configuration: mypyc/doc/conf.py

formats: [pdf, htmlzip, epub]

python:
   install:
   - requirements: docs/requirements-docs.txt
