from typing import Optional, Sequence, Tuple
from tracemalloc import _TraceTupleT, _FrameTupleT

def _get_object_traceback(__obj) -> Optional[Sequence[_FrameTupleT]]: ...
def _get_traces() -> Sequence[_TraceTupleT]: ...
def clear_traces() -> None: ...
def get_traceback_limit() -> int: ...
def get_traced_memory() -> Tuple[int, int]: ...
def get_tracemalloc_memory() -> int: ...
def is_tracing() -> bool: ...
def start(__nframe: int = ...) -> None: ...
def stop() -> None: ...
