[project]
name = 'typedpkg_namespace.nested'
version = '0.1'
description = 'Two namespace packages, one of them typed'

[tool.hatch.build]
include = ["**/*.py", "**/*.pyi", "**/py.typed"]

[build-system]
requires = ["hatchling==1.18"]
build-backend = "hatchling.build"
