# Stubs for email (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def message_from_string(s, *args, **kws): ...
def message_from_bytes(s, *args, **kws): ...
def message_from_file(fp, *args, **kws): ...
def message_from_binary_file(fp, *args, **kws): ...

# Names in __all__ with no definition:
#   base64mime
#   charset
#   encoders
#   errors
#   feedparser
#   generator
#   header
#   iterators
#   message
#   mime
#   parser
#   quoprimime
#   utils
