# Stubs for xml.etree.ElementPath (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

xpath_tokenizer_re = Undefined(Any)

def xpath_tokenizer(pattern, namespaces=None): pass
def get_parent_map(context): pass
def prepare_child(next, token): pass
def prepare_star(next, token): pass
def prepare_self(next, token): pass
def prepare_descendant(next, token): pass
def prepare_parent(next, token): pass
def prepare_predicate(next, token): pass

ops = Undefined(Any)

class _SelectorContext:
    parent_map = Undefined(Any)
    root = Undefined(Any)
    def __init__(self, root): pass

def iterfind(elem, path, namespaces=None): pass
def find(elem, path, namespaces=None): pass
def findall(elem, path, namespaces=None): pass
def findtext(elem, path, default=None, namespaces=None): pass
