# Stubs for yaml.reader (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from yaml.error import YAMLError

class ReaderError(YAMLError):
    name = ... # type: Any
    character = ... # type: Any
    position = ... # type: Any
    encoding = ... # type: Any
    reason = ... # type: Any
    def __init__(self, name, position, character, encoding, reason): ...

class Reader:
    name = ... # type: Any
    stream = ... # type: Any
    stream_pointer = ... # type: Any
    eof = ... # type: Any
    buffer = ... # type: Any
    pointer = ... # type: Any
    raw_buffer = ... # type: Any
    raw_decode = ... # type: Any
    encoding = ... # type: Any
    index = ... # type: Any
    line = ... # type: Any
    column = ... # type: Any
    def __init__(self, stream): ...
    def peek(self, index=0): ...
    def prefix(self, length=1): ...
    def forward(self, length=1): ...
    def get_mark(self): ...
    def determine_encoding(self): ...
    NON_PRINTABLE = ... # type: Any
    def check_printable(self, data): ...
    def update(self, length): ...
    def update_raw(self, size=1024): ...
