# Stubs for requests.packages.urllib3.util.connection (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

poll = Undefined(Any)
select = Undefined(Any)

def is_connection_dropped(conn): pass
def create_connection(address, timeout=Undefined, source_address=None, socket_options=None): pass
