# Stubs for requests.packages.urllib3.util.ssl_ (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .. import exceptions
import ssl

SSLError = exceptions.SSLError
InsecurePlatformWarning = exceptions.InsecurePlatformWarning
SSLContext = ssl.SSLContext

HAS_SNI = ...  # type: Any
create_default_context = ...  # type: Any
OP_NO_SSLv2 = ...  # type: Any
OP_NO_SSLv3 = ...  # type: Any
OP_NO_COMPRESSION = ...  # type: Any

def assert_fingerprint(cert, fingerprint): ...
def resolve_cert_reqs(candidate): ...
def resolve_ssl_version(candidate): ...
def create_urllib3_context(ssl_version=None, cert_reqs=..., options=None, ciphers=None): ...
def ssl_wrap_socket(sock, keyfile=None, certfile=None, cert_reqs=None, ca_certs=None,
                    server_hostname=None, ssl_version=None, ciphers=None, ssl_context=None): ...
