# Stubs for requests.packages.urllib3.util.ssl_ (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from .. import exceptions
import ssl

SSLError = exceptions.SSLError
InsecurePlatformWarning = exceptions.InsecurePlatformWarning
SSLContext = ssl.SSLContext

HAS_SNI = Undefined(Any)
create_default_context = Undefined(Any)
OP_NO_SSLv2 = Undefined(Any)
OP_NO_SSLv3 = Undefined(Any)
OP_NO_COMPRESSION = Undefined(Any)

def assert_fingerprint(cert, fingerprint): pass
def resolve_cert_reqs(candidate): pass
def resolve_ssl_version(candidate): pass
def create_urllib3_context(ssl_version=None, cert_reqs=Undefined, options=None, ciphers=None): pass
def ssl_wrap_socket(sock, keyfile=None, certfile=None, cert_reqs=None, ca_certs=None,
                    server_hostname=None, ssl_version=None, ciphers=None, ssl_context=None): pass
