# Stubs for requests.packages.urllib3.util.timeout (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .. import exceptions

TimeoutStateError = exceptions.TimeoutStateError

def current_time(): pass

class Timeout:
    DEFAULT_TIMEOUT = ...  # type: Any
    total = ...  # type: Any
    def __init__(self, total=None, connect=..., read=...): pass
    @classmethod
    def from_float(cls, timeout): pass
    def clone(self): pass
    def start_connect(self): pass
    def get_connect_duration(self): pass
    @property
    def connect_timeout(self): pass
    @property
    def read_timeout(self): pass
