# Stubs for requests.packages.urllib3.util.timeout (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from .. import exceptions

TimeoutStateError = exceptions.TimeoutStateError

def current_time(): pass

class Timeout:
    DEFAULT_TIMEOUT = Undefined(Any)
    total = Undefined(Any)
    def __init__(self, total=None, connect=Undefined, read=Undefined): pass
    @classmethod
    def from_float(cls, timeout): pass
    def clone(self): pass
    def start_connect(self): pass
    def get_connect_duration(self): pass
    @property
    def connect_timeout(self): pass
    @property
    def read_timeout(self): pass
