# Stubs for binascii (Python 2)

def a2b_uu(string: str) -> str: ...
def b2a_uu(data: str) -> str: ...
def a2b_base64(string: str) -> str: ...
def b2a_base64(data: str) -> str: ...
def a2b_qp(string: str, header: bool = None) -> str: ...
def b2a_qp(data: str, quotetabs: bool = None, istext: bool = None, header: bool = None) -> str: ...
def a2b_hqx(string: str) -> str: ...
def rledecode_hqx(data: str) -> str: ...
def rlecode_hqx(data: str) -> str: ...
def b2a_hqx(data: str) -> str: ...
def crc_hqx(data: str, crc: int) -> int: ...
def crc32(data: str, crc: int) -> int: ...
def b2a_hex(data: str) -> str: ...
def hexlify(data: str) -> str: ...
def a2b_hex(hexstr: str) -> str: ...
def unhexlify(hexstr: str) -> str: ...

class Error(Exception): ...
class Incomplete(Exception): ...
