from typing import Union
import io

_ANYFILE = Union[int, io.IOBase]

def fcntl(fd: _ANYFILE, op: int, arg: Union[int, str] = 0) -> Union[int, str]: ...

# TODO: arg: int or read-only buffer interface or read-write buffer interface
def ioctl(fd: _ANYFILE, op: int, arg: Union[int, str] = 0, mutate_flag: bool = True) -> Union[int, str]: ...

def flock(fd: _ANYFILE, op: int) -> None: ...
def lockf(fd: _ANYFILE, op: int, length: int = 0, start: int = 0, whence: int = 0) -> Union[int, str]: ...
