class hash(object):
    digest_size = 0
    block_size = 0
    def update(self, arg: str) -> None: ...
    def digest(self) -> str: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> hash: ...

def new(algo: str = None) -> hash: ...

def md5(s: str = None) -> hash: ...
def sha1(s: str = None) -> hash: ...
def sha224(s: str = None) -> hash: ...
def sha256(s: str = None) -> hash: ...
def sha384(s: str = None) -> hash: ...
def sha512(s: str = None) -> hash: ...

# TODO: tuple of str, unknown length
algorithms = ... # type: tuple
algorithms_guaranteed = ... # type: tuple
algorithms_available = ... # type: tuple

def pbkdf2_hmac(name: str, password: str, salt: str, rounds: int, dklen: int = None) -> str: ...
