# Stubs for hashlib

# NOTE: These are incomplete!

from abc import abstractmethod, ABCMeta
import typing

class Hash(metaclass=ABCMeta):
    @abstractmethod
    def algorithms(self) -> Sequence[str]: ...
    @abstractmethod
    def algorithms_guaranteed(self) -> Set[str]: ...
    @abstractmethod
    def algorithms_available(self) -> Set[str]: ...
    @abstractmethod
    def digest_size(self) -> bytes: ...
    @abstractmethod
    def block_size(self) -> bytes: ...
    @abstractmethod
    def update(self, arg: bytes) -> None: ...
    @abstractmethod
    def digest(self) -> bytes: ...
    @abstractmethod
    def hexdigest(self) -> str: ...
    @abstractmethod
    def copy(self) -> 'Hash': ...

def md5(arg: bytes = None) -> Hash: ...
def sha1(arg: bytes = None) -> Hash: ...
def sha224(arg: bytes = None) -> Hash: ...
def sha256(arg: bytes = None) -> Hash: ...
def sha384(arg: bytes = None) -> Hash: ...
def sha512(arg: bytes = None) -> Hash: ...
def pbkdff2_hmac(*args, **kwargs): ... # figure out the actual arguments for this

def new(name: str, data: bytes = None) -> Hash: ...
