# TODO incomplete
from typing import Any, List, Tuple

def isgenerator(object: Any) -> bool: ...

class _Frame:
    ...
_FrameRecord = Tuple[_Frame, str, int, str, List[str], int]

def currentframe() -> _FrameRecord: ...
def stack(context: int = None) -> List[_FrameRecord]: ...
