# Stubs for operator

# NOTE: These are incomplete!

from typing import Any

def add(a: Any, b: Any) -> Any: ...

def and_(a: Any, b: Any) -> Any: ...

def lt(a: Any, b: Any) -> Any: ...
def le(a: Any, b: Any) -> Any: ...
def eq(a: Any, b: Any) -> Any: ...
def ne(a: Any, b: Any) -> Any: ...
def gt(a: Any, b: Any) -> Any: ...
def ge(a: Any, b: Any) -> Any: ...
