from typing import Callable, Any, Tuple, Union

SIG_DFL = 0
SIG_IGN = 0
# TODO: SIG*
CTRL_C_EVENT = 0
CTRL_BREAK_EVENT = 0
GSIG = 0
ITIMER_REAL = 0
ITIMER_VIRTUAL = 0
ITIMER_PROF = 0

class ItimerError(IOError): ...

_HANDLER = Union[Callable[[int, Any], Any], int, None]

def alarm(time: float) -> int: ...
def getsignal(signalnum: int) -> _HANDLER: ...
def pause() -> None: ...
def setitimer(which: int, seconds: float, interval: float = None) -> Tuple[float, float]: ...
def getitimer(which: int) -> Tuple[float, float]: ...
def set_wakeup_fd(fd: int) -> None: ...
def siginterrupt(signalnum: int, flag: bool) -> None: ...
def signal(signalnum: int, handler: _HANDLER) -> None: ...
