# Stubs for sqlalchemy.util.compat (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from collections import namedtuple

py33 = ... # type: Any
py32 = ... # type: Any
py3k = ... # type: Any
py2k = ... # type: Any
py265 = ... # type: Any
jython = ... # type: Any
pypy = ... # type: Any
win32 = ... # type: Any
cpython = ... # type: Any
next = ... # type: Any
safe_kwarg = ... # type: Any

ArgSpec = namedtuple('ArgSpec', ['args', 'varargs', 'keywords', 'defaults'])

def inspect_getargspec(func): ...

string_types = ... # type: Any
binary_type = ... # type: Any
text_type = ... # type: Any
int_types = ... # type: Any
iterbytes = ... # type: Any

def u(s): ...
def ue(s): ...
def b(s): ...

callable = ... # type: Any

def callable(fn): ...
def cmp(a, b): ...

print_ = ... # type: Any
import_ = ... # type: Any
itertools_filterfalse = ... # type: Any
itertools_filter = ... # type: Any
itertools_imap = ... # type: Any

def b64encode(x): ...
def b64decode(x): ...

inspect_getargspec = ... # type: Any

def iterbytes(buf): ...
def u(s): ...
def ue(s): ...
def b(s): ...
def import_(*args): ...

cmp = ... # type: Any
reduce = ... # type: Any
b64encode = ... # type: Any
b64decode = ... # type: Any

def print_(*args, **kwargs): ...

time_func = ... # type: Any

def reraise(tp, value, tb=None, cause=None): ...
def raise_from_cause(exception, exc_info=None): ...
def raise_from_cause(exception, exc_info=None): ...

exec_ = ... # type: Any

def exec_(func_text, globals_, lcl=None): ...
def with_metaclass(meta, *bases): ...
def nested(*managers): ...
