# created from https://docs.python.org/2/library/os.html

from typing import List, Tuple, Union, Sequence, Mapping, IO, Any

error = OSError
name = ... # type: str
environ = ... # type: Mapping[str, str]

def chdir(path: str) -> None: ...
def fchdir(fd: int) -> None: ...
def getcwd() -> str: ...
def ctermid() -> str: ...
def getegid() -> int: ...
def geteuid() -> int: ...
def getgid() -> int: ...
def getgroups() -> List[int]: ...
def initgroups(username: str, gid: int) -> None: ...
def getlogin() -> str: ...
def getpgid(pid: int) -> int: ...
def getpgrp() -> int: ...
def getpid() -> int: ...
def getppid() -> int: ...
def getresuid() -> Tuple[int, int, int]: ...
def getresgid() -> Tuple[int, int, int]: ...
def getuid() -> int: ...
def getenv(varname: str, value: str = None) -> str: ...
def putenv(varname: str, value: str) -> None: ...
def setegid(egid: int) -> None: ...
def seteuid(euid: int) -> None: ...
def setgid(gid: int) -> None: ...
def setgroups(groups: Sequence[int]) -> None: ...

# TODO(MichalPokorny)
def setpgrp(*args) -> None: ...

def setpgid(pid: int, pgrp: int) -> None: ...
def setregid(rgid: int, egid: int) -> None: ...
def setresgid(rgid: int, egid: int, sgid: int) -> None: ...
def setresuid(ruid: int, euid: int, suid: int) -> None: ...
def setreuid(ruid: int, euid: int) -> None: ...
def getsid(pid: int) -> int: ...
def setsid() -> None: ...
def setuid(pid: int) -> None: ...

def strerror(code: int) -> str:
    raise ValueError()

def umask(mask: int) -> int: ...
def uname() -> Tuple[str, str, str, str, str]: ...
def unsetenv(varname: str) -> None: ...

# TODO(MichalPokorny)
def fdopen(fd: int, *args, **kwargs) -> IO[Any]: ...
def popen(command: str, *args, **kwargs) -> Optional[IO[Any]]: ...
def tmpfile() -> IO[Any]: ...

def popen2(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any]]: ...
def popen3(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any], IO[Any]]: ...
def popen4(cmd: str, *args, **kwargs) -> Tuple[IO[Any], IO[Any]]: ...

def close(fd: int) -> None: ...
def closerange(fd_low: int, fd_high: int) -> None: ...
def dup(fd: int) -> int: ...
def dup2(fd: int, fd2: int) -> None: ...
def fchmod(fd: int, mode: int) -> None: ...
def fchown(fd: int, uid: int, gid: int) -> None: ...
def fdatasync(fd: int) -> None: ...
def fpathconf(fd: int, name: str) -> None: ...

# TODO(prvak)
def fstat(fd: int) -> Any: ...
def fstatvfs(fd: int) -> Any: ...
def fsync(fd: int) -> None: ...
def ftruncate(fd: int, length: int) -> None: ...
def isatty(fd: int) -> bool: ...

def lseek(fd: int, pos: int, how: int) -> None: ...
SEEK_SET = 0
SEEK_CUR = 1
SEEK_END = 2

# TODO(prvak): maybe file should be unicode? (same with all other paths...)
def open(file: str, flags: int, mode: int = 0777) -> int: ...
def openpty() -> Tuple[int, int]: ...
def pipe() -> Tuple[int, int]: ...
def read(fd: int, n: int) -> str: ...
def tcgetpgrp(fd: int) -> int: ...
def tcsetpgrp(fd: int, pg: int) -> None: ...
def ttyname(fd: int) -> str: ...
def write(fd: int, str: str) -> int: ...

# TODO: O_*

def access(path: str, mode: int) -> bool: ...
F_OK = 0
R_OK = 0
W_OK = 0
X_OK = 0

def getcwdu() -> unicode: ...
def chflags(path: str, flags: int) -> None: ...
def chroot(path: str) -> None: ...
def chmod(path: str, mode: int) -> None: ...
def chown(path: str, uid: int, gid: int) -> None: ...
def lchflags(path: str, flags: int) -> None: ...
def lchmod(path: str, uid: int, gid: int) -> None: ...
def lchown(path: str, uid: int, gid: int) -> None: ...
def link(source: str, link_name: str) -> None: ...
def listdir(path: str) -> List[str]: ...

# TODO(MichalPokorny)
def lstat(path: str) -> Any: ...

def mkfifo(path: str, mode: int = 0666) -> None: ...
def mknod(filename: str, mode: int = 0600, device: int = 0) -> None: ...
def major(device: int) -> int: ...
def minor(device: int) -> int: ...
def makedev(major: int, minor: int) -> int: ...
def mkdir(path: str, mode: int = 0777) -> None: ...
def makedirs(path: str, mode: int = 0777) -> None: ...
def pathconf(path: str, name: str) -> str: ...

pathconf_names = ... # type: Mapping[str, int]

def readlink(path: str) -> str: ...
def remove(path: str) -> None: ...
def removedirs(path: str) -> None:
    raise OSError()
def rename(src: str, dst: str) -> None: ...
def renames(old: str, new: str) -> None: ...
def rmdir(path: str) -> None: ...

# TODO(MichalPokorny)
def stat(path: str) -> Any: ...

# TODO: stat_float_times, statvfs, tempnam, tmpnam, TMP_MAX, walk

def symlink(source: str, link_name: str) -> None: ...
def unlink(path: str) -> None: ...
def utime(path: str, times: Optional[Tuple[int, int]]) -> None: ...

def abort() -> None: ...
# TODO: exec*, _exit, EX_*

def fork() -> int:
    raise OSError()

def forkpty() -> Tuple[int, int]:
    raise OSError()

def kill(pid: int, sig: int) -> None: ...
def killpg(pgid: int, sig: int) -> None: ...
def nice(increment: int) -> int: ...

# TODO: plock, popen*, spawn*, P_*

def startfile(path: str, operation: str) -> None: ...
def system(command: str) -> int: ...
def times() -> Tuple[float, float, float, float, float]: ...
def wait() -> int: ...
def waitpid(pid: int, options: int) -> int:
    raise OSError()
# TODO: wait3, wait4, W...
def confstr(name: Union[str, int]) -> Optional[str]: ...
confstr_names = ... # type: Mapping[str, int]

def getloadavg() -> Tuple[float, float, float]:
    raise OSError()

def sysconf(name: Union[str, int]) -> int: ...
sysconf_names = ... # type: Mapping[str, int]

curdir = ... # type: str
pardir = ... # type: str
sep = ... # type: str
altsep = ... # type: str
extsep = ... # type: str
pathsep = ... # type: str
defpath = ... # type: str
linesep = ... # type: str
devnll = ... # type: str

def urandom(n: int) -> str: ...
