# Stubs for _subprocess

# NOTE: These are incomplete!

int CREATE_NEW_CONSOLE
int CREATE_NEW_PROCESS_GROUP
int STD_INPUT_HANDLE
int STD_OUTPUT_HANDLE
int STD_ERROR_HANDLE
int SW_HIDE
int STARTF_USESTDHANDLES
int STARTF_USESHOWWINDOW
