from mypy_extensions import u8

# TODO: Remove Buffer -- right now we have hacky support for BOTH the old and new APIs

class Buffer:
    def __init__(self, source: bytes = ...) -> None: ...
    def getvalue(self) -> bytes: ...

class ReadBuffer:
    def __init__(self, source: bytes) -> None: ...

class WriteBuffer:
    def getvalue(self) -> bytes: ...

def write_bool(data: WriteBuffer | Buffer, value: bool) -> None: ...
def read_bool(data: ReadBuffer | Buffer) -> bool: ...
def write_str(data: WriteBuffer | Buffer, value: str) -> None: ...
def read_str(data: ReadBuffer | Buffer) -> str: ...
def write_bytes(data: WriteBuffer | Buffer, value: bytes) -> None: ...
def read_bytes(data: ReadBuffer | Buffer) -> bytes: ...
def write_float(data: WriteBuffer | Buffer, value: float) -> None: ...
def read_float(data: ReadBuffer | Buffer) -> float: ...
def write_int(data: WriteBuffer | Buffer, value: int) -> None: ...
def read_int(data: ReadBuffer | Buffer) -> int: ...
def write_tag(data: WriteBuffer | Buffer, value: u8) -> None: ...
def read_tag(data: ReadBuffer | Buffer) -> u8: ...
def cache_version() -> u8: ...
