from typing import overload

def random() -> float: ...
def randint(a: int, b: int) -> int: ...
@overload
def randrange(stop: int, /) -> int: ...
@overload
def randrange(start: int, stop: int, /) -> int: ...

class Random:
    def __init__(self) -> None: ...
    def randint(self, a: int, b: int) -> int: ...
    @overload
    def randrange(self, stop: int, /) -> int: ...
    @overload
    def randrange(self, start: int, stop: int, /) -> int: ...
    def random(self) -> float: ...
