# Stubs for email._encoded_words (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

def decode_q(encoded): pass

class _QByteMap(dict):
    safe = Undefined(Any)
    def __missing__(self, key): pass

def encode_q(bstring): pass
def len_q(bstring): pass
def decode_b(encoded): pass
def encode_b(bstring): pass
def len_b(bstring): pass
def decode(ew): pass
def encode(string, charset='', encoding=None, lang=''): pass
