# Stubs for email._parseaddr (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def parsedate_tz(data): pass
def parsedate(data): pass
def mktime_tz(data): pass
def quote(str): pass

class AddrlistClass:
    specials = ...  # type: Any
    pos = ...  # type: Any
    LWS = ...  # type: Any
    CR = ...  # type: Any
    FWS = ...  # type: Any
    atomends = ...  # type: Any
    phraseends = ...  # type: Any
    field = ...  # type: Any
    commentlist = ...  # type: Any
    def __init__(self, field): pass
    def gotonext(self): pass
    def getaddrlist(self): pass
    def getaddress(self): pass
    def getrouteaddr(self): pass
    def getaddrspec(self): pass
    def getdomain(self): pass
    def getdelimited(self, beginchar, endchars, allowcomments=True): pass
    def getquote(self): pass
    def getcomment(self): pass
    def getdomainliteral(self): pass
    def getatom(self, atomends=None): pass
    def getphraselist(self): pass

class AddressList(AddrlistClass):
    addresslist = ...  # type: Any
    def __init__(self, field): pass
    def __len__(self): pass
    def __add__(self, other): pass
    def __iadd__(self, other): pass
    def __sub__(self, other): pass
    def __isub__(self, other): pass
    def __getitem__(self, index): pass
