# Stubs for email._policybase (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class _PolicyBase:
    def __init__(self, **kw): pass
    def clone(self, **kw): pass
    def __setattr__(self, name, value): pass
    def __add__(self, other): pass

class Policy(_PolicyBase):
    raise_on_defect = Undefined(Any)
    linesep = Undefined(Any)
    cte_type = Undefined(Any)
    max_line_length = Undefined(Any)
    def handle_defect(self, obj, defect): pass
    def register_defect(self, obj, defect): pass
    def header_max_count(self, name): pass
    def header_source_parse(self, sourcelines): pass
    def header_store_parse(self, name, value): pass
    def header_fetch_parse(self, name, value): pass
    def fold(self, name, value): pass
    def fold_binary(self, name, value): pass

class Compat32(Policy):
    def header_source_parse(self, sourcelines): pass
    def header_store_parse(self, name, value): pass
    def header_fetch_parse(self, name, value): pass
    def fold(self, name, value): pass
    def fold_binary(self, name, value): pass

compat32 = Undefined(Any)
