# Stubs for email.base64mime (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

def header_length(bytearray): pass
def header_encode(header_bytes, charset=''): pass
def body_encode(s, maxlinelen=76, eol=Undefined): pass
def decode(string): pass

body_decode = Undefined(Any)
decodestring = Undefined(Any)
