# Stubs for email.charset (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def add_charset(charset, header_enc=None, body_enc=None, output_charset=None): pass
def add_alias(alias, canonical): pass
def add_codec(charset, codecname): pass

class Charset:
    input_charset = ...  # type: Any
    header_encoding = ...  # type: Any
    body_encoding = ...  # type: Any
    output_charset = ...  # type: Any
    input_codec = ...  # type: Any
    output_codec = ...  # type: Any
    def __init__(self, input_charset=...): pass
    def __eq__(self, other): pass
    def __ne__(self, other): pass
    def get_body_encoding(self): pass
    def get_output_charset(self): pass
    def header_encode(self, string): pass
    def header_encode_lines(self, string, maxlengths): pass
    def body_encode(self, string): pass
