# Stubs for email.charset (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

def add_charset(charset, header_enc=None, body_enc=None, output_charset=None): pass
def add_alias(alias, canonical): pass
def add_codec(charset, codecname): pass

class Charset:
    input_charset = Undefined(Any)
    header_encoding = Undefined(Any)
    body_encoding = Undefined(Any)
    output_charset = Undefined(Any)
    input_codec = Undefined(Any)
    output_codec = Undefined(Any)
    def __init__(self, input_charset=Undefined): pass
    def __eq__(self, other): pass
    def __ne__(self, other): pass
    def get_body_encoding(self): pass
    def get_output_charset(self): pass
    def header_encode(self, string): pass
    def header_encode_lines(self, string, maxlengths): pass
    def body_encode(self, string): pass
