# Stubs for email.contentmanager (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class ContentManager:
    get_handlers = Undefined(Any)
    set_handlers = Undefined(Any)
    def __init__(self): pass
    def add_get_handler(self, key, handler): pass
    def get_content(self, msg, *args, **kw): pass
    def add_set_handler(self, typekey, handler): pass
    def set_content(self, msg, obj, *args, **kw): pass

raw_data_manager = Undefined(Any)

def get_text_content(msg, errors=''): pass
def get_non_text_content(msg): pass
def get_message_content(msg): pass
def get_and_fixup_unknown_message_content(msg): pass
def set_text_content(msg, string, subtype='', charset='', cte=None, disposition=None,
                     filename=None, cid=None, params=None, headers=None): pass
def set_message_content(msg, message, subtype='', cte=None, disposition=None, filename=None,
                        cid=None, params=None, headers=None): pass
def set_bytes_content(msg, data, maintype, subtype, cte='', disposition=None, filename=None,
                      cid=None, params=None, headers=None): pass
