# Stubs for email.encoders (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def encode_base64(msg): pass
def encode_quopri(msg): pass
def encode_7or8bit(msg): pass
def encode_noop(msg): pass
