# Stubs for email.errors (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class MessageError(Exception): pass
class MessageParseError(MessageError): pass
class HeaderParseError(MessageParseError): pass
class BoundaryError(MessageParseError): pass
class MultipartConversionError(MessageError, TypeError): pass
class CharsetError(MessageError): pass

class MessageDefect(ValueError):
    line = Undefined(Any)
    def __init__(self, line=None): pass

class NoBoundaryInMultipartDefect(MessageDefect): pass
class StartBoundaryNotFoundDefect(MessageDefect): pass
class CloseBoundaryNotFoundDefect(MessageDefect): pass
class FirstHeaderLineIsContinuationDefect(MessageDefect): pass
class MisplacedEnvelopeHeaderDefect(MessageDefect): pass
class MissingHeaderBodySeparatorDefect(MessageDefect): pass

MalformedHeaderDefect = Undefined(Any)

class MultipartInvariantViolationDefect(MessageDefect): pass
class InvalidMultipartContentTransferEncodingDefect(MessageDefect): pass
class UndecodableBytesDefect(MessageDefect): pass
class InvalidBase64PaddingDefect(MessageDefect): pass
class InvalidBase64CharactersDefect(MessageDefect): pass

class HeaderDefect(MessageDefect):
    def __init__(self, *args, **kw): pass

class InvalidHeaderDefect(HeaderDefect): pass
class HeaderMissingRequiredValue(HeaderDefect): pass

class NonPrintableDefect(HeaderDefect):
    non_printables = Undefined(Any)
    def __init__(self, non_printables): pass

class ObsoleteHeaderDefect(HeaderDefect): pass
class NonASCIILocalPartDefect(HeaderDefect): pass
