# Stubs for email.feedparser (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class BufferedSubFile:
    def __init__(self): pass
    def push_eof_matcher(self, pred): pass
    def pop_eof_matcher(self): pass
    def close(self): pass
    def readline(self): pass
    def unreadline(self, line): pass
    def push(self, data): pass
    def pushlines(self, lines): pass
    def __iter__(self): pass
    def __next__(self): pass

class FeedParser:
    policy = Undefined(Any)
    def __init__(self, _factory=None, *, policy=Undefined): pass
    def feed(self, data): pass
    def close(self): pass

class BytesFeedParser(FeedParser):
    def feed(self, data): pass
