# Stubs for email.generator (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class Generator:
    maxheaderlen = Undefined(Any)
    policy = Undefined(Any)
    def __init__(self, outfp, mangle_from_=True, maxheaderlen=None, *, policy=None): pass
    def write(self, s): pass
    def flatten(self, msg, unixfrom=False, linesep=None): pass
    def clone(self, fp): pass

class BytesGenerator(Generator):
    def write(self, s): pass

class DecodedGenerator(Generator):
    def __init__(self, outfp, mangle_from_=True, maxheaderlen=78, fmt=None): pass
