# Stubs for email.header (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def decode_header(header): pass
def make_header(decoded_seq, maxlinelen=None, header_name=None, continuation_ws=''): pass

class Header:
    def __init__(self, s=None, charset=None, maxlinelen=None, header_name=None,
                 continuation_ws='', errors=''): pass
    def __eq__(self, other): pass
    def __ne__(self, other): pass
    def append(self, s, charset=None, errors=''): pass
    def encode(self, splitchars='', maxlinelen=None, linesep=''): pass

class _ValueFormatter:
    def __init__(self, headerlen, maxlen, continuation_ws, splitchars): pass
    def newline(self): pass
    def add_transition(self): pass
    def feed(self, fws, string, charset): pass

class _Accumulator(list):
    def __init__(self, initial_size=0): pass
    def push(self, fws, string): pass
    def pop_from(self, i=0): pass
    def __len__(self): pass
    def reset(self, startval=None): pass
    def is_onlyws(self): pass
    def part_count(self): pass
