# Stubs for email.iterators (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def walk(self): pass
def body_line_iterator(msg, decode=False): pass
def typed_subpart_iterator(msg, maintype='', subtype=None): pass
