# Stubs for email.policy (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from email._policybase import Policy, Compat32, compat32
from email._policybase import Policy

Policy = Policy
Compat32 = Compat32
compat32 = compat32

class EmailPolicy(Policy):
    refold_source = Undefined(Any)
    header_factory = Undefined(Any)
    content_manager = Undefined(Any)
    def __init__(self, **kw): pass
    def header_max_count(self, name): pass
    def header_source_parse(self, sourcelines): pass
    def header_store_parse(self, name, value): pass
    def header_fetch_parse(self, name, value): pass
    def fold(self, name, value): pass
    def fold_binary(self, name, value): pass

default = Undefined(Any)
strict = Undefined(Any)
SMTP = Undefined(Any)
HTTP = Undefined(Any)
