# Stubs for requests.packages.urllib3.exceptions (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class HTTPError(Exception): pass
class HTTPWarning(Warning): pass

class PoolError(HTTPError):
    pool = Undefined(Any)
    def __init__(self, pool, message): pass
    def __reduce__(self): pass

class RequestError(PoolError):
    url = Undefined(Any)
    def __init__(self, pool, url, message): pass
    def __reduce__(self): pass

class SSLError(HTTPError): pass
class ProxyError(HTTPError): pass
class DecodeError(HTTPError): pass
class ProtocolError(HTTPError): pass

ConnectionError = Undefined(Any)

class MaxRetryError(RequestError):
    reason = Undefined(Any)
    def __init__(self, pool, url, reason=None): pass

class HostChangedError(RequestError):
    retries = Undefined(Any)
    def __init__(self, pool, url, retries=3): pass

class TimeoutStateError(HTTPError): pass
class TimeoutError(HTTPError): pass
class ReadTimeoutError(TimeoutError, RequestError): pass
class ConnectTimeoutError(TimeoutError): pass
class EmptyPoolError(PoolError): pass
class ClosedPoolError(PoolError): pass
class LocationValueError(ValueError, HTTPError): pass

class LocationParseError(LocationValueError):
    location = Undefined(Any)
    def __init__(self, location): pass

class ResponseError(HTTPError):
    GENERIC_ERROR = Undefined(Any)
    SPECIFIC_ERROR = Undefined(Any)

class SecurityWarning(HTTPWarning): pass
class InsecureRequestWarning(SecurityWarning): pass
class SystemTimeWarning(SecurityWarning): pass
class InsecurePlatformWarning(SecurityWarning): pass
