# Stubs for requests.packages.urllib3.poolmanager (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from .request import RequestMethods

class PoolManager(RequestMethods):
    proxy = Undefined(Any)
    connection_pool_kw = Undefined(Any)
    pools = Undefined(Any)
    def __init__(self, num_pools=10, headers=None, **connection_pool_kw): pass
    def __enter__(self): pass
    def __exit__(self, exc_type, exc_val, exc_tb): pass
    def clear(self): pass
    def connection_from_host(self, host, port=None, scheme=''): pass
    def connection_from_url(self, url): pass
    # TODO: This was the original signature -- copied another one from base class to fix complaint.
    # def urlopen(self, method, url, redirect=True, **kw): pass
    def urlopen(self, method, url, body=None, headers=None, encode_multipart=True, multipart_boundary=None, **kw): pass

class ProxyManager(PoolManager):
    proxy = Undefined(Any)
    proxy_headers = Undefined(Any)
    def __init__(self, proxy_url, num_pools=10, headers=None, proxy_headers=None, **connection_pool_kw): pass
    def connection_from_host(self, host, port=None, scheme=''): pass
    # TODO: This was the original signature -- copied another one from base class to fix complaint.
    # def urlopen(self, method, url, redirect=True, **kw): pass
    def urlopen(self, method, url, body=None, headers=None, encode_multipart=True, multipart_boundary=None, **kw): pass

def proxy_from_url(url, **kw): pass
