from typing import Any

def enable() -> None: ...
def disable() -> None: ...
def isenabled() -> bool: ...
def collect(generation: int = ...) -> int: ...
def set_debug(flags: int) -> None: ...
def get_debug() -> int: ...
def get_objects() -> list[Any]: ...
def set_threshold(threshold0: int, threshold1: int = ..., threshold2: int = ...) -> None: ...
def get_count() -> tuple[int, int, int]: ...
def get_threshold() -> tuple[int, int, int]: ...
def get_referrers(*objs: Any) -> list[Any]: ...
def get_referents(*objs: Any) -> list[Any]: ...
def is_tracked(obj: Any) -> bool: ...

garbage: list[Any]

DEBUG_STATS: int
DEBUG_COLLECTABLE: int
DEBUG_UNCOLLECTABLE: int
DEBUG_INSTANCES: int
DEBUG_OBJECTS: int
DEBUG_SAVEALL: int
DEBUG_LEAK: int
