from typing import AnyStr, Iterator

def glob(pathname: AnyStr) -> list[AnyStr]: ...
def iglob(pathname: AnyStr) -> Iterator[AnyStr]: ...
def glob1(dirname: str | unicode, pattern: AnyStr) -> list[AnyStr]: ...
def glob0(dirname: str | unicode, basename: AnyStr) -> list[AnyStr]: ...
def has_magic(s: str | unicode) -> bool: ...  # undocumented
