# Stubs for requests.api (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def request(method, url, **kwargs): pass
def get(url, **kwargs): pass
def options(url, **kwargs): pass
def head(url, **kwargs): pass
def post(url, data=None, json=None, **kwargs): pass
def put(url, data=None, **kwargs): pass
def patch(url, data=None, **kwargs): pass
def delete(url, **kwargs): pass
