# Stubs for requests.hooks (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

HOOKS = Undefined(Any)

def default_hooks(): pass
def dispatch_hook(key, hooks, hook_data, **kwargs): pass
