# Stubs for requests.status_codes (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from . import structures

LookupDict = structures.LookupDict

codes = Undefined(Any)
