# Stubs for yaml.error (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Mark:
    name = ... # type: Any
    index = ... # type: Any
    line = ... # type: Any
    column = ... # type: Any
    buffer = ... # type: Any
    pointer = ... # type: Any
    def __init__(self, name, index, line, column, buffer, pointer): ...
    def get_snippet(self, indent=4, max_length=75): ...

class YAMLError(Exception): ...

class MarkedYAMLError(YAMLError):
    context = ... # type: Any
    context_mark = ... # type: Any
    problem = ... # type: Any
    problem_mark = ... # type: Any
    note = ... # type: Any
    def __init__(self, context=None, context_mark=None, problem=None, problem_mark=None, note=None): ...
