# Stubs for yaml.nodes (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Node:
    tag = ... # type: Any
    value = ... # type: Any
    start_mark = ... # type: Any
    end_mark = ... # type: Any
    def __init__(self, tag, value, start_mark, end_mark): ...

class ScalarNode(Node):
    id = ... # type: Any
    tag = ... # type: Any
    value = ... # type: Any
    start_mark = ... # type: Any
    end_mark = ... # type: Any
    style = ... # type: Any
    def __init__(self, tag, value, start_mark=None, end_mark=None, style=None): ...

class CollectionNode(Node):
    tag = ... # type: Any
    value = ... # type: Any
    start_mark = ... # type: Any
    end_mark = ... # type: Any
    flow_style = ... # type: Any
    def __init__(self, tag, value, start_mark=None, end_mark=None, flow_style=None): ...

class SequenceNode(CollectionNode):
    id = ... # type: Any

class MappingNode(CollectionNode):
    id = ... # type: Any
