[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    # Officially supported pybind11 version. This is pinned to guarantee 100% reproducible CI.
    # As a result, the version needs to be bumped manually at will.
    "pybind11==3.0.1",
]

build-backend = "setuptools.build_meta"
