# Stubs for webbrowser (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Error(Exception): ...

def register(name, klass, instance=None, update_tryorder=1): ...
def get(using=None): ...
def open(url, new=0, autoraise=True): ...
def open_new(url): ...
def open_new_tab(url): ...

class BaseBrowser:
    args = ... # type: Any
    name = ... # type: Any
    basename = ... # type: Any
    def __init__(self, name=''): ...
    def open(self, url, new=0, autoraise=True): ...
    def open_new(self, url): ...
    def open_new_tab(self, url): ...

class GenericBrowser(BaseBrowser):
    name = ... # type: Any
    args = ... # type: Any
    basename = ... # type: Any
    def __init__(self, name): ...
    def open(self, url, new=0, autoraise=True): ...

class BackgroundBrowser(GenericBrowser):
    def open(self, url, new=0, autoraise=True): ...

class UnixBrowser(BaseBrowser):
    raise_opts = ... # type: Any
    background = ... # type: Any
    redirect_stdout = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    def open(self, url, new=0, autoraise=True): ...

class Mozilla(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Galeon(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    background = ... # type: Any

class Chrome(UnixBrowser):
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Opera(UnixBrowser):
    raise_opts = ... # type: Any
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any

class Elinks(UnixBrowser):
    remote_args = ... # type: Any
    remote_action = ... # type: Any
    remote_action_newwin = ... # type: Any
    remote_action_newtab = ... # type: Any
    background = ... # type: Any
    redirect_stdout = ... # type: Any

class Konqueror(BaseBrowser):
    def open(self, url, new=0, autoraise=True): ...

class Grail(BaseBrowser):
    def open(self, url, new=0, autoraise=True): ...

class WindowsDefault(BaseBrowser):
    def open(self, url, new=0, autoraise=True): ...

class MacOSX(BaseBrowser):
    name = ... # type: Any
    def __init__(self, name): ...
    def open(self, url, new=0, autoraise=True): ...

class MacOSXOSAScript(BaseBrowser):
    def __init__(self, name): ...
    def open(self, url, new=0, autoraise=True): ...
