# Stubs for email.mime.application (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from email.mime.nonmultipart import MIMENonMultipart

class MIMEApplication(MIMENonMultipart):
    def __init__(self, _data, _subtype='', _encoder=..., **_params): ...
