# Stubs for email.mime.audio (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined
from email.mime.nonmultipart import MIMENonMultipart

class MIMEAudio(MIMENonMultipart):
    def __init__(self, _audiodata, _subtype=None, _encoder=Undefined, **_params): pass
