# Stubs for email.mime.nonmultipart (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from email.mime.base import MIMEBase

class MIMENonMultipart(MIMEBase):
    def attach(self, payload): ...
