__all__ = ["rgb_to_yiq", "yiq_to_rgb", "rgb_to_hls", "hls_to_rgb", "rgb_to_hsv", "hsv_to_rgb"]

def rgb_to_yiq(r: float | int, g: float | int, b: float | int) -> tuple[float, float, float]: ...
def yiq_to_rgb(y: float | int, i: float | int, q: float | int) -> tuple[float, float, float]: ...
def rgb_to_hls(r: float | int, g: float | int, b: float | int) -> tuple[float, float, float]: ...
def hls_to_rgb(h: float | int, l: float | int, s: float | int) -> tuple[float, float, float]: ...
def rgb_to_hsv(r: float | int, g: float | int, b: float | int) -> tuple[float, float, float]: ...
def hsv_to_rgb(h: float | int, s: float | int, v: float | int) -> tuple[float, float, float]: ...

# TODO undocumented
ONE_SIXTH: float | int
ONE_THIRD: float | int
TWO_THIRD: float | int
