from typing import Any, Dict, List, Optional

_ModuleGlobals = Dict[str, Any]

def getline(filename: str, lineno: int, module_globals: Optional[_ModuleGlobals] = ...) -> str: ...
def clearcache() -> None: ...
def getlines(filename: str, module_globals: Optional[_ModuleGlobals] = ...) -> List[str]: ...
def checkcache(filename: Optional[str] = ...) -> None: ...
def updatecache(filename: str, module_globals: Optional[_ModuleGlobals] = ...) -> List[str]: ...
def lazycache(filename: str, module_globals: _ModuleGlobals) -> bool: ...
